name: acu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2  
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.16
  google_nav_bar: ^5.0.7
  hidden_drawer_menu: ^3.0.1
  image_picker: ^1.1.2
  http: ^1.3.0
  get_storage: ^2.1.1
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.12
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"  
  adaptive_icon_background: "#FFFFFF"  
  adaptive_icon_foreground: "lib/assets/logo.png" 

