name: acu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5  
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.16
  google_nav_bar: ^5.0.7
  hidden_drawer_menu: ^3.0.1
  image_picker: ^1.1.2
  http: ^1.3.0
  get_storage: ^2.1.1
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.12
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
